version: '3.9'
services:

  spring-container-database:
    image: postgres:15.6
    container_name: spring-container-database
    ports:
      - ${DB_PORT}:5432
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - pg-data:/var/lib/postgresql/data

volumes:
  pg-data:
