### Login
POST {{base-url}}/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "{{password}}"
}

### FIND ALL PRODUCTS
GET {{base-url}}/products
Authorization: Bearer {{admin-token}}

### CREATE PRODUCTS
POST {{base-url}}/products
Authorization: Bearer {{admin-token}}
Content-Type: application/json

{
  "name": "producto1"
}
